# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "rustdns"
version = "0.1.0"
authors = ["Andrew Brampton <brampton@gmail.com>"]
categories = ["encoding", "network-programming"]
description = "A DNS parsing library"
edition = "2018"
keywords = ["dns", "idna", "serialization"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bramp/rustdns"

[workspace]
members = [
    "generate_tests",   # Used to generate test data (by querying real servers)
    "dig",              # Example dig client
    # "nslookup",         # Example nslookup client
]

[dependencies]
strum = "0.21"         # Simple macros for making Enum better
strum_macros = "0.21"
num-traits = "0.2.14"  # More macros for making Enum better
num-derive = "0.3.3"
idna = "0.2.3"         # Encodes internation domain names
byteorder = "1.4.3"    # Simplifies the binary parsing
rand = "0.8.3"
bytes = "1.0.1"
nom = "6.1.2"

# Used for the clients
hyper = { version = "0.14.9", features = ["client", "runtime", "http1", "http2"] } # Used by the DoH client
http = "0.2.4"
url = "2.2.2"

# Needed for DNS over HTTP (DoH)
base64 = "0.13.0"      
hyper-alpn = "0.3.0"      # Uses tokio-rustls
time = "0.2.26"
async-trait = "0.1.50"
nom_locate = "3.0.1"


###


[dev-dependencies]
pretty_assertions = "0.7.2"
serde = { version = "1.0.126", features = ["derive"] }
serde_yaml = "0.8.17"
hex = "0.4.3"
regex = "1.5.4"  # Used to cleanup the test cases for better comparison.
tokio = { version = "1.6.1", features = ["macros", "rt-multi-thread"] }
