[package]
name = "rustdns"
version = "0.1.0"
authors = ["Andrew Brampton <brampton@gmail.com>"]
edition = "2018"
default-run = "rustdns"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding8 = "0.3.2"
strum = "0.20"
strum_macros = "0.20"
num-traits = "0.2.14"
num-derive = "0.3.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_yaml = "0.8.17"
hex = "0.4.3"
punycode = "0.4.1"
idna = "0.2.3"
regex = "1.5.4"

[[bin]]
name = "rustdns"
path = "src/rustdns/main.rs"

[[bin]]
name = "generate_tests"
path = "src/generate_tests/main.rs"
